config/routes.rb
Rails.application.routes.draw do
  
  root "movies#index"
  resources :movies do
  	resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :title, :released_on, :duration, presence: true

  validates :description, length: {minimum: 25}

  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :rating, inclusion: { in: RATINGS }

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= 300000000').order(total_gross: :desc)
  end

  def self.flops
    where('total_gross < 50000000').order(total_gross: :asc)
  end

  def self.recently_added
    order('created_at desc').limit(3)
  end

  def flop?
    total_gross.blank? || total_gross < 50000000
  end

  def average_stars
    reviews.average(:stars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true

  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: { 
  	in: STARS,
  	message: "must be between 1 and 5"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save 
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

private

  def movie_params
    params.require(:movie).
      permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :set_movie

	def index
		@reviews = @movie.reviews
	end

	def new
		@review = @movie.reviews.new
	end

	def create
		@review = @movie.reviews.new(review_params)
		if @review.save
			redirect_to movie_reviews_path(@movie),
				notice: "Thanks for your review!"
		else
			render :new
		end
	end
end

private 

def review_params
	params.require(:review).permit(:name, :comment, :stars)
end

def set_movie
	@movie = Movie.find(params[:movie_id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop!')
    else
      number_to_currency(movie.total_gross)
    end
  end

  def image_for(movie)
    if movie.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(movie.image_file_name)
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def format_average_stars(movie)
		if movie.average_stars.nil?
			content_tag(:strong, 'No reivews')
		else
			pluralize(movie.average_stars, 'star')
		end
	end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2016. Design By
    <%= link_to 'Armard Bellamy', 'http://www.armardbellamy.com' %>
  </p>
  <p>
    Demo App
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="wrapper">

      <% if flash[:notice] %>
        <%= render '/layouts/flashes' %>
      <% end %>

      <% if flash[:alert] %>
        <%= render '/layouts/flashes' %>
      <% end %>

      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
          <%= yield %>
        </section>
      </div>

    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>

  <%= render '/shared/errors', object: @movie %>
  
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_select :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.text_field :image_file_name %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
          <tr>
            <th>Average Rating</th>
            <td><%= format_average_stars(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article id="movie" class="movie">
  <header>
    <%= image_for(@movie) %>

    <h1><%= @movie.title %></h1>
    
    <h2>Released: <%= @movie.released_on %></h2>
  </header>

  <p>
    <%= @movie.description %>
  </p>
  
  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %> 
  </h3>
  
  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>
  
  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>
  
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  <h3>Average Review</h3>
  <p>
    <%= format_average_stars(@movie) %>
  </p>

  <%= link_to pluralize(@movie.reviews.size, "review"),
              movie_reviews_path(@movie) %>

  <footer>
    <nav>
      <%= link_to 'Write Review', new_movie_review_path(@movie),
            class: 'button ok review' %>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
  </footer>
</article>

app/views/reviews/index.html.erb
<header id="content-header">
	<h1>Reviews for <%= link_to@movie.title, @movie %></h1>
</header>
<ol id="reviews">
	<% @reviews.each do |review| %>
		<li>
				<span class="review"><%= pluralize(review.stars, 'star') %></span>
				<span class="user"><%= review.name %></span>
				<span class="date"><%= time_ago_in_words(review.created_at) %> ago </span>
				<p>
					&quot;<%= review.comment %>&quot;
				</p>
		</li>
	<% end %>
</ol>

app/views/reviews/new.html.erb
<header>
	<h1>New Review for <%= link_to @movie.title, @movie %></h1>
</header>

<%= form_for([@movie, @review]) do |f| %>

	<%= render "shared/errors", object: @review %>

	<fieldset>
	<ol>
		<li class="required">
			<%= f.label :name %>
			<%= f.text_field :name, size: 40, autofocus: true %>
		</li>
		<li class="required stars">
			<%= f.label :stars %>
			<%= f.select :stars, Review::STARS, prompt: "Pick one" %>
		</li>
		<li>
			<%= f.label :comment %>
			<%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
		</li>
	</ol>
	<p>
		<%= f.submit 'Post Review' %>
		<%= link_to 'Cancel', @movie, class: 'button' %>
	</p>
	</fieldset>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>